---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: launch-vm-job
  namespace: aap
spec:
  connection_secret: aapaccess
  job_template_name: vm-prov-centos-tmp
  extra_vars: 